FROM node:20-alpine

WORKDIR /app

COPY ProjectManagement/ProjectManagement.Web/package*.json ./
RUN npm install

COPY ProjectManagement/ProjectManagement.Web/ ./

RUN npm run build -- --configuration production

RUN npm install -g serve

CMD ["sh", "-c", "serve -s dist/*/browser -l 4200"]

EXPOSE 4200